version: "3.9"
services:
  web:
    build: .
    image: audio-downloader-web:latest
    container_name: audio-downloader-web
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./src/static:/app/src/static
      - ./downloads:/app/downloads
    restart: unless-stopped